### ISSUE TITLE
backend service port taken by traefik

### ISSUE THREAD

**Issue by frank3stein** [udacity/CNAND_nd064_C4_Observability_Starter_Files#2]
At the moment when you deploy the cluster, the backend service can not get port assigned. This is the project

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: martinezi/metrics-backend
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
```

```bash
➜  Project_Starter_Files-Building_a_Metrics_Dashboard git:(main) ✗ kubectl describe pod svclb-backend-service-zjnx4
Name:           svclb-backend-service-zjnx4
Namespace:      default
Priority:       0
Node:           <none>
Labels:         app=svclb-backend-service
                controller-revision-hash=9fcfcdcf5
                pod-template-generation=1
                svccontroller.k3s.cattle.io/svcname=backend-service
Annotations:    <none>
Status:         Pending
IP:             
IPs:            <none>
Controlled By:  DaemonSet/svclb-backend-service
Containers:
  lb-port-80:
    Image:      rancher/klipper-lb:v0.1.2
    Port:       80/TCP
    Host Port:  80/TCP
    Environment:
      SRC_PORT:    80
      DEST_PROTO:  TCP
      DEST_PORT:   80
      DEST_IP:     10.43.116.140
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-dq4k4 (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  default-token-dq4k4:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-dq4k4
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     CriticalAddonsOnly op=Exists
                 node-role.kubernetes.io/master:NoSchedule op=Exists
                 node.kubernetes.io/disk-pressure:NoSchedule op=Exists
                 node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                 node.kubernetes.io/not-ready:NoExecute op=Exists
                 node.kubernetes.io/pid-pressure:NoSchedule op=Exists
                 node.kubernetes.io/unreachable:NoExecute op=Exists
                 node.kubernetes.io/unschedulable:NoSchedule op=Exists
Events:
  Type     Reason            Age   From               Message
  ----     ------            ----  ----               -------
  Warning  FailedScheduling  6h6m  default-scheduler  0/1 nodes are available: 1 node(s) didn't have free ports for the requested pod ports.

```
I have done some research, and it seems traefik is already is using the port. I am not sure how to proceed, to get the backend to work.
